[package]
name = "gossip"
version = "0.8.0-unstable"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
default-run = "gossip"
edition = "2021"

[features]
default = ["rustls-tls"]
lang-cjk = []
video-ffmpeg = [ "egui-video", "sdl2" ]

native-tls = [ "reqwest/native-tls", "tungstenite/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = [ "reqwest/rustls-tls", "tungstenite/rustls-tls-webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots"]

[patch.crates-io]
# override egui crate for egui_video dependency
egui = { git =  "https://github.com/mikedilger/egui", rev = "538088439c7c507fe49c730eab84ddd85e147391" }
# Use the master branch of SDL2 to include a fix related to clang (and XCode after 14.2)
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", rev = "27cd1fd67c811e06b9d997a77bb6089a1b65070d" }

[dependencies]
async-trait = "0.1"
base64 = "0.21"
dashmap = "5.4"
dirs = "5.0"
eframe = { git = "https://github.com/mikedilger/egui", rev = "538088439c7c507fe49c730eab84ddd85e147391", features = [ "persistence" ] }
egui-winit = { git = "https://github.com/mikedilger/egui", rev = "538088439c7c507fe49c730eab84ddd85e147391", features = [ "default" ] }
egui_extras = { git = "https://github.com/mikedilger/egui", rev = "538088439c7c507fe49c730eab84ddd85e147391", features = [ "image", "svg" ] }
egui-video = { git = "https://github.com/mikedilger/egui-video", rev = "5a7297138dce16425c7dc7a8eab4d39d79088aba",  features = [ "from_bytes" ], optional = true }
encoding_rs = "0.8"
fallible-iterator = "0.2"
filetime = "0.2"
futures = "0.3"
futures-util = "0.3"
gossip-relay-picker = { git = "https://github.com/mikedilger/gossip-relay-picker", rev = "f4dd0604af80848da6b78b0df0d386aa459895cd" }
hex = "0.4"
http = "0.2"
humansize = "2.1"
image = { version = "0.24.6", features = [ "png", "jpeg" ] }
kamadak-exif = "0.5"
lazy_static = "1.4"
linkify = "0.9"
lmdb-rkv = "0.14"
lmdb-rkv-sys = "0.11"
memoize = "0.4"
mime = "0.3"
nostr-types = { git = "https://github.com/mikedilger/nostr-types", rev = "ad369f2674eddca433d8ee6004de10c1cc47778a", features = [ "speedy" ] }
parking_lot = "0.12"
qrcode = { git = "https://github.com/mikedilger/qrcode-rust", rev = "519b77b3efa3f84961169b47d3de08c5ddd86548" }
rand = "0.8"
regex = "1.8"
reqwest = { version = "0.11", default-features=false, features = ["brotli", "deflate", "gzip", "json"] }
rhai = { version = "1.15", features = [ "std", "sync" ]}
rusqlite = { version = "0.29", features = ["bundled", "chrono", "serde_json"] }
sdl2 = { version = "0.35.2", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
speedy = { git = "https://github.com/mikedilger/speedy", rev = "b8b713a7006958616dd3ef3ba63217740b4b09c2" }
time = { version = "0.3", features = [ "formatting", "macros" ] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "std", "env-filter" ] }
tokio-tungstenite = { version = "0.19", default-features = false, features = [ "connect", "handshake" ] }
tungstenite = { version = "0.19", default-features = false }
url = "2.4"
vecmap-rs = "0.1"
zeroize = "1.6"

[target.'cfg(windows)'.dependencies]
normpath = "1.1"

# Force scrypt to build with release-like speed even in dev mode
[profile.dev.package.scrypt]
opt-level = 3
debug-assertions = false
overflow-checks = false

[package.metadata.deb]
section = "web"
assets = [
    ["target/release/gossip", "/usr/bin/", "755"],
    ["packaging/debian/gossip.desktop", "/usr/share/applications/gossip.desktop", "644"],
]
features = [ "lang-cjk" ]
